# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20160318_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
