# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20160318_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
