# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
